/**
 * Hand-made example problems for workstream W2b's activities, so they can
 * be built and tested before the generators exist. Shown by the dev page
 * ?scene=fixtures&kind=<activity kind>.
 *
 * They follow the generators' conventions (headers of
 * core/generators/number.ts and more.ts) and show what each activity does:
 *   compare   answer a side's number → tap a pan; "<" "=" ">" → crocodile
 *             cards; words ("more", "fewer", "the same") → cards
 *   tensOnes  visual tens = ones = 0 → build the answer on the mat; else read
 *             (with piles to add from, or pieces to take away, when the
 *             text is a sum starting from the picture: "34 + 20 = ?")
 *   groups    by skill and tier: see, build (groups / arrays tier 3) or
 *             make groups from a loose pile (group-div)
 *   share     tap the pile to deal; answer how many each, from the cards
 *   fraction  answers "half" / "quarter" / "third" / "whole" or yes / no;
 *             visual shaded = 0 → shade the parts, then OK; choices like
 *             "circle:2:1" / "rect:4:1:u" → picture cards (W2b extras)
 */
import type { Problem } from '../core/problem';

export const FIXTURES_B: Problem[] = [
  // ---------------- compare ----------------
  {
    skill: 'compare-10',
    tier: 1,
    activity: 'compare',
    say: { text: 'Which side has more acorns?' },
    answer: 7,
    choices: [4, 7],
    visual: { type: 'compare', left: 4, right: 7, asObjects: 'acorn' },
    explain: { text: '{b} is more than {a}!', vals: { a: 4, b: 7 } },
    key: 'fx-compare:4v7',
  },
  {
    skill: 'compare-10',
    tier: 2,
    activity: 'compare',
    say: { text: 'Does the Saucepan Man have more, fewer or the same saucepans as Moon-Face?' },
    answer: 'fewer',
    choices: ['more', 'fewer', 'the same'],
    visual: { type: 'compare', left: 6, right: 8, asObjects: 'saucepan' },
    explain: { text: '{a} is fewer than {b}.', vals: { a: 6, b: 8 } },
    key: 'fx-compare:6v8',
  },
  {
    skill: 'compare-10',
    tier: 3,
    activity: 'compare',
    say: { text: 'Which number is smaller?' },
    answer: 5,
    choices: [9, 5],
    visual: { type: 'compare', left: 9, right: 5 },
    explain: { text: '{b} is smaller than {a}.', vals: { a: 9, b: 5 } },
    key: 'fx-compare:9v5',
  },
  {
    skill: 'compare-100',
    tier: 1,
    activity: 'compare',
    say: { text: 'Which is bigger? Count the bundles.' },
    answer: 43,
    choices: [34, 43],
    visual: { type: 'compare', left: 34, right: 43, asObjects: 'stick' },
    explain: { text: '{b} is bigger than {a}.', vals: { a: 34, b: 43 } },
    key: 'fx-compare:34v43',
  },
  {
    skill: 'compare-100',
    tier: 3,
    activity: 'compare',
    say: { text: 'Which crocodile goes in the gap? It eats the bigger number.' },
    text: '56 ? 47',
    answer: '>',
    choices: ['<', '=', '>'],
    visual: { type: 'compare', left: 56, right: 47 },
    explain: { text: '{a} is bigger than {b}.', vals: { a: 56, b: 47 } },
    key: 'fx-compare:56>47',
  },
  {
    skill: 'compare-100',
    tier: 3,
    activity: 'compare',
    say: { text: 'Which crocodile goes in the gap?' },
    text: '25 ? 25',
    answer: '=',
    choices: ['<', '=', '>'],
    visual: { type: 'compare', left: 25, right: 25 },
    explain: { text: '{a} is the same as {b}.', vals: { a: 25, b: 25 } },
    key: 'fx-compare:25=25',
  },

  // ---------------- tensOnes ----------------
  {
    skill: 'tens-ones',
    tier: 1,
    activity: 'tensOnes',
    say: { text: 'Make {n} with bundles and sticks.', vals: { n: 23 } },
    answer: 23,
    choices: [23, 32, 5, 22],
    visual: { type: 'tensOnes', tens: 0, ones: 0 },
    explain: { text: '2 tens and 3 ones make {n}!', vals: { n: 23 } },
    key: 'fx-tens:build23',
  },
  {
    skill: 'tens-ones',
    tier: 2,
    activity: 'tensOnes',
    say: { text: 'How many sticks are there?' },
    answer: 47,
    choices: [47, 74, 11, 46],
    visual: { type: 'tensOnes', tens: 4, ones: 7 },
    explain: { text: '4 tens and 7 ones make {n}!', vals: { n: 47 } },
    key: 'fx-tens:read47',
  },
  {
    skill: 'tens-ones',
    tier: 3,
    activity: 'tensOnes',
    say: { text: '{n} is 40 and how many more?', vals: { n: 47 } },
    text: '47 = 40 + ?',
    answer: 7,
    choices: [7, 4, 40, 47],
    visual: { type: 'tensOnes', tens: 4, ones: 7 },
    explain: { text: '{n} is 40 and 7.', vals: { n: 47 } },
    key: 'fx-tens:part47',
  },
  {
    skill: 'times-10',
    tier: 1,
    activity: 'tensOnes',
    say: { text: 'How many sticks in {n} bundles of ten?', vals: { n: 6 } },
    answer: 60,
    choices: [60, 6, 16, 50],
    visual: { type: 'tensOnes', tens: 6, ones: 0 },
    explain: { text: '{n} tens make 60!', vals: { n: 6 } },
    key: 'fx-tens:6x10',
  },
  {
    skill: 'tens-ones',
    tier: 1,
    activity: 'tensOnes',
    say: { text: 'Make {n} with bundles and sticks.', vals: { n: 9 } },
    answer: 9,
    choices: [9, 90, 19, 8],
    visual: { type: 'tensOnes', tens: 0, ones: 0 },
    explain: { text: '9 ones make {n}!', vals: { n: 9 } },
    key: 'fx-tens:build9',
  },
  {
    skill: 'add-tens',
    tier: 1,
    activity: 'tensOnes',
    say: { text: 'Here is {a}. Add {t} more bundles of ten. What is {a} add {b}?', vals: { a: 34, t: 2, b: 20 } },
    text: '34 + 20 = ?',
    answer: 54,
    choices: [54, 36, 44, 64],
    visual: { type: 'tensOnes', tens: 3, ones: 4 },
    explain: { text: '{a} add {b} makes {c}!', vals: { a: 34, b: 20, c: 54 } },
    key: 'fx-tens:34+20',
  },
  {
    skill: 'sub-2d1d',
    tier: 1,
    activity: 'tensOnes',
    say: { text: 'What is {a} take away {b}?', vals: { a: 37, b: 4 } },
    text: '37 − 4 = ?',
    answer: 33,
    choices: [33, 34, 41, 3],
    visual: { type: 'tensOnes', tens: 3, ones: 7 },
    explain: { text: '{a} take away {b} leaves {c}!', vals: { a: 37, b: 4, c: 33 } },
    key: 'fx-tens:37-4',
  },

  // ---------------- groups ----------------
  {
    skill: 'groups',
    tier: 2,
    activity: 'groups',
    say: { text: 'There are {g} plates with {e} Google Buns on each. How many Google Buns altogether?', vals: { g: 3, e: 4 } },
    text: '4 + 4 + 4 = ?',
    answer: 12,
    choices: [12, 7, 11, 16],
    visual: { type: 'groups', groups: 3, each: 4, layout: 'groups', prop: 'googleBun' },
    explain: { text: '4 add 4 add 4 makes 12!' },
    key: 'fx-groups:3x4',
  },
  {
    skill: 'groups',
    tier: 3,
    activity: 'groups',
    say: { text: 'Make {g} equal groups, with {e} apples in each. How many altogether?', vals: { g: 4, e: 3 } },
    answer: 12,
    choices: [12, 7, 15, 9],
    visual: { type: 'groups', groups: 4, each: 3, layout: 'groups', prop: 'apple' },
    explain: { text: '4 groups of 3 make 12!' },
    key: 'fx-groups:build4x3',
  },
  {
    skill: 'arrays',
    tier: 1,
    activity: 'groups',
    say: { text: 'How many rows of toy soldiers are there?' },
    answer: 3,
    choices: [3, 5, 15, 4],
    visual: { type: 'groups', groups: 3, each: 5, layout: 'array', prop: 'soldier' },
    explain: { text: '3 rows of 5 soldiers.' },
    key: 'fx-arrays:rows3x5',
  },
  {
    skill: 'arrays',
    tier: 2,
    activity: 'groups',
    say: { text: '{g} rows of {e}. How many toy soldiers?', vals: { g: 3, e: 5 } },
    text: '3 × 5 = ?',
    answer: 15,
    choices: [15, 8, 10, 35],
    visual: { type: 'groups', groups: 3, each: 5, layout: 'array', prop: 'soldier' },
    explain: { text: '3 fives make 15!' },
    key: 'fx-arrays:3x5',
  },
  {
    skill: 'arrays',
    tier: 3,
    activity: 'groups',
    say: { text: 'Build an array: {g} rows, with {e} toy soldiers in each row. How many altogether?', vals: { g: 2, e: 4 } },
    text: '2 × 4 = ?',
    answer: 8,
    choices: [8, 6, 12, 9],
    visual: { type: 'groups', groups: 2, each: 4, layout: 'array', prop: 'soldier' },
    explain: { text: '2 rows of 4 make 8!' },
    key: 'fx-arrays:build2x4',
  },
  {
    skill: 'times-2',
    tier: 1,
    activity: 'groups',
    say: { text: '{g} cushions on the slippery-slip, 2 children on each. How many children?', vals: { g: 6 } },
    text: '6 × 2 = ?',
    answer: 12,
    choices: [12, 8, 10, 14],
    visual: { type: 'groups', groups: 6, each: 2, layout: 'groups', prop: 'teddy' },
    explain: { text: '6 twos make 12!' },
    key: 'fx-times2:6',
  },
  {
    skill: 'group-div',
    tier: 1,
    activity: 'groups',
    say: { text: 'There are {t} snowballs. Put them in groups of {s}. How many groups can you make?', vals: { t: 10, s: 2 } },
    answer: 5,
    choices: [5, 2, 10, 4],
    visual: { type: 'groups', groups: 5, each: 2, layout: 'groups', prop: 'snowball' },
    explain: { text: '10 makes 5 groups of 2.' },
    key: 'fx-groupdiv:10/2',
  },
  {
    skill: 'times-10',
    tier: 1,
    activity: 'groups',
    say: { text: 'There are {n} bundles of {m} sticks. Count in {m}s. How many sticks altogether?', vals: { n: 4, m: 10 } },
    text: '4 × 10 = ?',
    answer: 40,
    choices: [40, 14, 30, 50],
    visual: { type: 'groups', groups: 4, each: 10, layout: 'groups', prop: 'stick' },
    explain: { text: '10, 20, 30, 40. 4 bundles of 10 make 40!' },
    key: 'fx-times10:4',
  },

  // ---------------- share ----------------
  {
    skill: 'share',
    tier: 1,
    activity: 'share',
    say: { text: 'Share {t} snowballs fairly between 2. How many each?', vals: { t: 8 } },
    answer: 4,
    choices: [4, 2, 6, 8],
    visual: { type: 'share', total: 8, between: 2, prop: 'snowball' },
    explain: { text: '8 shared between 2 is 4 each!' },
    key: 'fx-share:8/2',
  },
  {
    skill: 'share',
    tier: 2,
    activity: 'share',
    say: { text: 'Share {t} toffee shocks fairly between 3. How many each?', vals: { t: 12 } },
    answer: 4,
    choices: [4, 3, 6, 9],
    visual: { type: 'share', total: 12, between: 3, prop: 'toffee' },
    explain: { text: '12 shared between 3 is 4 each!' },
    key: 'fx-share:12/3',
  },
  {
    skill: 'share',
    tier: 2,
    activity: 'share',
    say: { text: 'Share {t} pop biscuits fairly between 5. How many each?', vals: { t: 20 } },
    answer: 4,
    choices: [4, 5, 3, 15],
    visual: { type: 'share', total: 20, between: 5, prop: 'popBiscuit' },
    explain: { text: '20 shared between 5 is 4 each!' },
    key: 'fx-share:20/5',
  },
  {
    skill: 'share',
    tier: 3,
    activity: 'share',
    say: { text: 'What is {t} divided by {b}?', vals: { t: 15, b: 3 } },
    text: '15 ÷ 3 = ?',
    answer: 5,
    choices: [5, 3, 12, 6],
    visual: { type: 'share', total: 15, between: 3, prop: 'apple' },
    explain: { text: '15 divided by 3 is 5!' },
    key: 'fx-share:15/3',
  },
  {
    skill: 'fractions',
    tier: 3,
    activity: 'share',
    say: { text: 'What is a quarter of {t} acorns?', vals: { t: 12 } },
    text: '¼ of 12 = ?',
    answer: 3,
    choices: [3, 4, 6, 12],
    visual: { type: 'share', total: 12, between: 4, prop: 'acorn' },
    explain: { text: 'A quarter of {t} is {c}! {n} equal groups of {c}.', vals: { t: 12, c: 3, n: 4 } },
    key: 'fx-share:quarter-of-12',
  },

  // ---------------- fraction ----------------
  {
    skill: 'fractions',
    tier: 1,
    activity: 'fraction',
    say: { text: 'Silky cut the ice-pie. Is the shaded piece a half?' },
    answer: 'no',
    choices: ['yes', 'no'],
    visual: { type: 'fraction', shape: 'circle', parts: 2, shaded: 1, equal: false },
    explain: { text: 'No! The {n} parts are not the same size, so they are not halves.', vals: { n: 2 } },
    key: 'fx-frac:unequal-half',
  },
  {
    skill: 'fractions',
    tier: 2,
    activity: 'fraction',
    say: { text: 'What fraction of the birthday cake is shaded?' },
    answer: 'quarter',
    choices: ['half', 'quarter', 'whole'],
    visual: { type: 'fraction', shape: 'rect', parts: 4, shaded: 1, equal: true },
    explain: { text: '{n} equal parts. One part is a quarter!', vals: { n: 4 } },
    key: 'fx-frac:name-quarter',
  },
  {
    skill: 'fractions',
    tier: 4,
    activity: 'fraction',
    say: { text: 'What fraction of the ice-pie is shaded?' },
    answer: 'third',
    choices: ['half', 'quarter', 'third', 'whole'],
    visual: { type: 'fraction', shape: 'circle', parts: 3, shaded: 1, equal: true },
    explain: { text: '{n} equal parts. One part is a third!', vals: { n: 3 } },
    key: 'fx-frac:name-third',
  },
  {
    skill: 'fractions',
    tier: 1,
    activity: 'fraction',
    say: { text: 'Which ice-pie is cut in half?' },
    text: 'a half',
    answer: 'circle:2:1',
    choices: ['circle:2:1:u', 'circle:2:1', 'circle:4:1'],
    visual: { type: 'none' },
    explain: { text: 'Two equal parts. That is a half!' },
    key: 'fx-frac:which-half',
  },
  {
    skill: 'fractions',
    tier: 2,
    activity: 'fraction',
    say: { text: 'Colour in a quarter of the cake.' },
    answer: 'quarter',
    choices: ['half', 'quarter', 'whole'],
    visual: { type: 'fraction', shape: 'rect', parts: 4, shaded: 0 },
    explain: { text: 'One of four equal parts is a quarter!' },
    key: 'fx-frac:shade-quarter',
  },
  {
    skill: 'fractions',
    tier: 2,
    activity: 'fraction',
    say: { text: 'Colour in half of the cake.' },
    answer: 'half',
    choices: ['half', 'quarter', 'whole'],
    visual: { type: 'fraction', shape: 'rect', parts: 4, shaded: 0 },
    explain: { text: 'Two of four parts is a half!' },
    key: 'fx-frac:shade-half-of-4',
  },
  {
    skill: 'fractions',
    tier: 4,
    activity: 'fraction',
    say: { text: 'Colour in a third of the ice-pie.' },
    answer: 'third',
    choices: ['half', 'quarter', 'third'],
    visual: { type: 'fraction', shape: 'circle', parts: 3, shaded: 0 },
    explain: { text: 'One of three equal parts is a third!' },
    key: 'fx-frac:shade-third',
  },
];
