/**
 * Hand-made example problems for workstream W2a's activities, so they can
 * be built and tested before the generators exist. Shown by the dev page
 * ?scene=fixtures&kind=<activity kind>.
 *
 * Each covers a different shape of problem: small and big counts, rows and
 * scatter, adding and taking away, one and two ten frames, short and long
 * number lines, cherry and bar models, typed sums with and without a picture.
 */
import type { Problem } from '../core/problem';

const ex = (text: string, vals?: Record<string, number>) => ({ text, vals });

export const FIXTURES_A: Problem[] = [
  // ---- count ----
  {
    skill: 'count-10',
    tier: 1,
    activity: 'count',
    say: ex('How many acorns can you count?'),
    answer: 4,
    choices: [3, 4, 5, 6],
    visual: { type: 'objects', groups: [{ prop: 'acorn', count: 4 }], layout: 'row' },
    explain: ex('{n} acorns!', { n: 4 }),
    key: 'fx-count:4',
  },
  {
    skill: 'count-10',
    tier: 3,
    activity: 'count',
    say: ex('How many pop biscuits can you count?'),
    answer: 9,
    choices: [8, 10, 9, 7],
    visual: { type: 'objects', groups: [{ prop: 'popBiscuit', count: 9 }], layout: 'scatter' },
    explain: ex('{n} pop biscuits!', { n: 9 }),
    key: 'fx-count:9s',
  },
  {
    skill: 'add-10',
    tier: 2,
    activity: 'count',
    say: ex('Moon-Face has {a} toffee shocks. Then {b} more come. How many now?', { a: 5, b: 3 }),
    answer: 8,
    choices: [7, 8, 9, 2],
    visual: { type: 'objects', groups: [{ prop: 'toffee', count: 5 }, { prop: 'toffee', count: 3 }], op: '+' },
    explain: ex('{a} add {b} makes {c}!', { a: 5, b: 3, c: 8 }),
    key: 'fx-count:5+3',
  },
  {
    skill: 'sub-10',
    tier: 2,
    activity: 'count',
    say: ex('Silky has {a} apples. {b} roll away. How many are left?', { a: 7, b: 3 }),
    answer: 4,
    choices: [4, 5, 3, 10],
    visual: { type: 'objects', groups: [{ prop: 'apple', count: 7, gone: 3 }], op: '-' },
    explain: ex('{a} take away {b} leaves {c}!', { a: 7, b: 3, c: 4 }),
    key: 'fx-count:7-3',
  },
  {
    skill: 'count-20',
    tier: 1,
    activity: 'count',
    say: ex('How many teacups can you count?'),
    answer: 16,
    choices: [15, 16, 17, 14],
    visual: { type: 'objects', groups: [{ prop: 'teacup', count: 16 }], layout: 'row' },
    explain: ex('{n} teacups!', { n: 16 }),
    key: 'fx-count:16',
  },

  // ---- tenFrame ----
  {
    skill: 'bonds-10',
    tier: 1,
    activity: 'tenFrame',
    say: ex('Silky’s tin holds 10 pop biscuits. It has {a}. How many more to fill it?', { a: 6 }),
    answer: 4,
    choices: [4, 6, 5, 3],
    visual: { type: 'tenFrame', frames: [6], prop: 'popBiscuit' },
    explain: ex('{a} and {b} make 10!', { a: 6, b: 4 }),
    key: 'fx-tf:fill6',
  },
  {
    skill: 'add-10',
    tier: 3,
    activity: 'tenFrame',
    say: ex('Moon-Face has {a} acorns. Then {b} more come. How many now?', { a: 4, b: 3 }),
    text: '4 + 3 = ?',
    answer: 7,
    choices: [6, 7, 8, 1],
    visual: { type: 'tenFrame', frames: [4], add: 3, prop: 'acorn' },
    explain: ex('{a} add {b} makes {c}!', { a: 4, b: 3, c: 7 }),
    key: 'fx-tf:4+3',
  },
  {
    skill: 'sub-10',
    tier: 3,
    activity: 'tenFrame',
    say: ex('The Saucepan Man has {a} saucepans. {b} roll away. How many are left?', { a: 9, b: 4 }),
    text: '9 − 4 = ?',
    answer: 5,
    choices: [5, 6, 4, 10],
    visual: { type: 'tenFrame', frames: [9], remove: 4, prop: 'saucepan' },
    explain: ex('{a} take away {b} leaves {c}!', { a: 9, b: 4, c: 5 }),
    key: 'fx-tf:9-4',
  },
  {
    skill: 'subitise',
    tier: 3,
    activity: 'tenFrame',
    say: ex('How many counters in the frame?'),
    answer: 7,
    choices: [6, 7, 8, 5],
    visual: { type: 'tenFrame', frames: [7] },
    explain: ex('{n}! Five and two more.', { n: 7 }),
    key: 'fx-tf:read7',
  },
  {
    skill: 'bridge-add',
    tier: 1,
    activity: 'tenFrame',
    say: ex('What is {a} add {b}? Fill the first tin first.', { a: 8, b: 5 }),
    text: '8 + 5 = ?',
    answer: 13,
    choices: [12, 13, 14, 3],
    visual: { type: 'tenFrame', frames: [8, 0], add: 5 },
    explain: ex('{a} add {b} makes {c}!', { a: 8, b: 5, c: 13 }),
    key: 'fx-tf:8+5',
  },
  {
    skill: 'bridge-sub',
    tier: 1,
    activity: 'tenFrame',
    say: ex('What is {a} take away {b}?', { a: 13, b: 5 }),
    text: '13 − 5 = ?',
    answer: 8,
    choices: [7, 8, 9, 18],
    visual: { type: 'tenFrame', frames: [10, 3], remove: 5 },
    explain: ex('{a} take away {b} leaves {c}!', { a: 13, b: 5, c: 8 }),
    key: 'fx-tf:13-5',
  },
  {
    skill: 'bonds-20',
    tier: 1,
    activity: 'tenFrame',
    say: ex('{a} and how many more make 20?', { a: 14 }),
    answer: 6,
    choices: [6, 5, 7, 4],
    visual: { type: 'tenFrame', frames: [10, 4] },
    explain: ex('{a} and {b} make 20!', { a: 14, b: 6 }),
    key: 'fx-tf:fill14',
  },

  // ---- numberLine ----
  {
    skill: 'sub-10',
    tier: 4,
    activity: 'numberLine',
    say: ex('Start at {a}. Jump back {b}. Where do you land?', { a: 7, b: 3 }),
    text: '7 − 3 = ?',
    answer: 4,
    choices: [4, 5, 3, 10],
    visual: { type: 'numberLine', from: 0, to: 10, start: 7, step: -1 },
    explain: ex('{a} take away {b} leaves {c}!', { a: 7, b: 3, c: 4 }),
    key: 'fx-nl:7-3',
  },
  {
    skill: 'one-more',
    tier: 2,
    activity: 'numberLine',
    say: ex('What is one more than {a}?', { a: 6 }),
    answer: 7,
    choices: [5, 6, 7, 8],
    visual: { type: 'numberLine', from: 0, to: 10, start: 6, step: 1 },
    explain: ex('One more than {a} is {b}!', { a: 6, b: 7 }),
    key: 'fx-nl:6+1',
  },
  {
    skill: 'add-20',
    tier: 2,
    activity: 'numberLine',
    say: ex('Start at {a}. Hop on {b}. Where do you land?', { a: 13, b: 4 }),
    text: '13 + 4 = ?',
    answer: 17,
    choices: [16, 17, 18, 9],
    visual: { type: 'numberLine', from: 0, to: 20, start: 13, step: 1 },
    explain: ex('{a} add {b} makes {c}!', { a: 13, b: 4, c: 17 }),
    key: 'fx-nl:13+4',
  },
  {
    skill: 'count-100',
    tier: 2,
    activity: 'numberLine',
    say: ex('Start at {a}. Hop on three tens. Where do you land?', { a: 20 }),
    text: '20 + 30 = ?',
    answer: 50,
    choices: [40, 50, 60, 23],
    visual: { type: 'numberLine', from: 0, to: 100, start: 20, step: 10 },
    explain: ex('{a} add {b} makes {c}!', { a: 20, b: 30, c: 50 }),
    key: 'fx-nl:20+30',
  },

  // ---- partWhole ----
  {
    skill: 'bonds-10',
    tier: 2,
    activity: 'partWhole',
    say: ex('{a} and how many more make 10?', { a: 3 }),
    answer: 7,
    choices: [7, 3, 8, 6],
    visual: { type: 'partWhole', whole: 10, parts: [3, null], model: 'cherry' },
    explain: ex('{a} and {b} make 10!', { a: 3, b: 7 }),
    key: 'fx-pw:3+?=10',
  },
  {
    skill: 'part-whole-10',
    tier: 2,
    activity: 'partWhole',
    say: ex('Dame Washalot has two baskets: {a} socks and {b} socks. How many altogether?', { a: 4, b: 2 }),
    answer: 6,
    choices: [5, 6, 7, 2],
    visual: { type: 'partWhole', whole: null, parts: [4, 2], model: 'cherry' },
    explain: ex('{a} and {b} make {c}!', { a: 4, b: 2, c: 6 }),
    key: 'fx-pw:4+2',
  },
  {
    skill: 'part-whole-10',
    tier: 3,
    activity: 'partWhole',
    say: ex('The whole is {w}. One part is {a}. What is the other part?', { w: 9, a: 5 }),
    answer: 4,
    choices: [4, 5, 3, 14],
    visual: { type: 'partWhole', whole: 9, parts: [5, null], model: 'bar' },
    explain: ex('{a} and {b} make {w}!', { a: 5, b: 4, w: 9 }),
    key: 'fx-pw:bar9-5',
  },
  {
    skill: 'bonds-20',
    tier: 3,
    activity: 'partWhole',
    say: ex('{a} and what make 20?', { a: 13 }),
    answer: 7,
    choices: [6, 7, 8, 3],
    visual: { type: 'partWhole', whole: 20, parts: [null, 13], model: 'bar' },
    explain: ex('{b} and {a} make 20!', { a: 13, b: 7 }),
    key: 'fx-pw:bar20-13',
  },

  // ---- numberPad ----
  {
    skill: 'add-10',
    tier: 5,
    activity: 'numberPad',
    say: ex('What is {a} add {b}?', { a: 6, b: 3 }),
    text: '6 + 3 = ?',
    answer: 9,
    choices: [8, 9, 10, 3],
    visual: { type: 'none' },
    explain: ex('{a} add {b} makes {c}!', { a: 6, b: 3, c: 9 }),
    key: 'fx-np:6+3',
  },
  {
    skill: 'bonds-10',
    tier: 4,
    activity: 'numberPad',
    say: ex('{a} add what makes 10?', { a: 2 }),
    text: '2 + ? = 10',
    answer: 8,
    choices: [8, 7, 9, 2],
    visual: { type: 'none' },
    explain: ex('{a} and {b} make 10!', { a: 2, b: 8 }),
    key: 'fx-np:2+?',
  },
  {
    skill: 'add-2d1d',
    tier: 4,
    activity: 'numberPad',
    say: ex('What is {a} add {b}?', { a: 36, b: 7 }),
    text: '36 + 7 = ?',
    answer: 43,
    choices: [42, 43, 44, 33],
    visual: { type: 'none' },
    explain: ex('{a} add {b} makes {c}!', { a: 36, b: 7, c: 43 }),
    key: 'fx-np:36+7',
  },
  {
    skill: 'sub-20',
    tier: 4,
    activity: 'numberPad',
    say: ex('How many are left?'),
    text: '15 − 4 = ?',
    answer: 11,
    visual: { type: 'tenFrame', frames: [10, 5], remove: 4 },
    explain: ex('{a} take away {b} leaves {c}!', { a: 15, b: 4, c: 11 }),
    key: 'fx-np:15-4',
  },
];
